version: '3.4'

services:
  comp-geo-julia:
    build: 
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 80:80
    volumes: 
      - ".:/project/"
      - ./packages.jl:/project/packages.jl
      - ./requirements.txt:/project/requirements.txt